In [59]:
import pandas as pd
import numpy as np
import requests
from bs4 import BeautifulSoup

In [60]:
teamstats = pd.DataFrame()
for i in range(2004, 2023):
    x = pd.read_html('https://www.teamrankings.com/nfl/stat/points-per-game?date=%i-03-15' % (i+1))
    df = x[0]
    df['Year'] = df.columns[2]
    df = df[['Team', str(i), 'Year']]
    df = df.rename(columns = {str(i): 'TeamPPG'})
    x = pd.read_html('https://www.teamrankings.com/nfl/stat/opponent-points-per-game?date=%i-03-15' % (i+1))
    df2 = x[0]
    df2['Year'] = df2.columns[2]
    df2 = df2[['Team', str(i), 'Year']]
    df2 = df2.rename(columns = {str(i): 'teamOPPG'})
    df = pd.merge(df, df2, on = ['Team', 'Year'])
    x = pd.read_html('https://www.teamrankings.com/nfl/stat/yards-per-game?date=%i-03-15' % (i+1))
    df2 = x[0]
    df2['Year'] = df2.columns[2]
    df2 = df2[['Team', str(i), 'Year']]
    df2 = df2.rename(columns = {str(i): 'TeamYPG'})
    df = pd.merge(df, df2, on = ['Team', 'Year'])
    x = pd.read_html('https://www.teamrankings.com/nfl/stat/passing-play-pct?date=%i-03-15' % (i+1))
    df2 = x[0]
    df2['Year'] = df2.columns[2]
    df2 = df2[['Team', str(i), 'Year']]
    df2 = df2.rename(columns = {str(i): 'TeamPassPct'})
    df2['TeamPassPct'] = df2['TeamPassPct'].replace('%', '', regex = True)
    df = pd.merge(df, df2, on = ['Team', 'Year'])
    teamstats = pd.concat([teamstats, df])

In [61]:
teamstats['Year'] = teamstats['Year'].astype(int)
teamstats['TeamPassPct'] = teamstats['TeamPassPct'].astype(float)

In [62]:
teamstats = teamstats.reset_index().drop(columns = 'index')

In [64]:
teamstats

             Team  TeamPPG  Year  teamOPPG  TeamYPG  TeamPassPct
0    Indianapolis     31.9  2004      21.9    404.4        56.97
1     Kansas City     30.2  2004      27.2    418.3        54.45
2     New England     27.5  2004      16.4    352.5        49.02
3     LA Chargers     27.2  2004      19.6    350.6        47.90
4       Green Bay     25.9  2004      24.2    391.4        57.96
..            ...      ...   ...       ...      ...          ...
603     Tennessee     17.5  2022      21.1    296.8        50.91
604       NY Jets     17.4  2022      18.6    318.2        62.29
605       Houston     17.0  2022      24.7    283.5        60.79
606  Indianapolis     17.0  2022      25.1    311.6        60.20
607        Denver     16.9  2022      21.1    325.1        58.81

[608 rows x 6 columns]

In [65]:
teamstats.to_csv('teamstats.csv')